using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using CsvHelper;

namespace TheEisenhowerMatrix
{
    // ALL FILES RELATED OPERATIONS - managing csv, reading from, writing to handled here.
    public static class DataManager
    {
        // path to root project directory
        private static readonly string PathToProject = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.FullName;

        public static void SaveToCSV(ToDoMatrix toDoMatrix)
        {
            // saving List<ToDoItem> prepared by Matrix PrepareItemsForSaving() method to .csv file:

            using StreamWriter FileWriter = new($"{PathToProject}\\data\\{toDoMatrix.Name}.csv");
            using (CsvWriter CSVWriter = new(FileWriter, CultureInfo.CurrentCulture))
            {
                CSVWriter.WriteRecords(toDoMatrix.PrepareItemsForSaving());
            }
            //
        }

        public static List<ToDoItem> ReadFromCSV(string filename)
        {
            // reading from existing csv file to create items from it - with mapping to exact fields to avoid bugs.
            List<ToDoItem> records = new();

            using StreamReader FileReader = new($"{PathToProject}\\data\\{filename}.csv");
            using (CsvReader CSVReader = new(FileReader, CultureInfo.CurrentCulture))
            {
                CSVReader.Read();
                CSVReader.ReadHeader();
                while (CSVReader.Read())
                {
                    string message = CSVReader.GetField<string>("Message");
                    bool isImportant = CSVReader.GetField<bool>("IsImportant");
                    DateTime deadline = CSVReader.GetField<DateTime>("Deadline");
                    ItemStatus status = CSVReader.GetField<ItemStatus>("Status");

                    records.Add(new ToDoItem(message, isImportant, deadline, status));
                }
            }

            return records;
            //
        }

        public static Dictionary<int, string> GetSavedData()
        {
            // getting all the saved files in the data directory for user to choose from:

            Dictionary<int, string> savedData = new();
            int counter = 1;

            foreach (string data in Directory.GetFiles($"{PathToProject}\\data", "*.csv"))
            {
                savedData.Add(counter, data.Split("\\data\\")[1]);
                counter++;
            }

            return savedData;
            //
        }

        public static ToDoMatrix ImportUserData(string filename)
        {
            // creating new "old" matrix based on List<ToDoItem> generated by ReadFromCSV() method:
            List<ToDoItem> itemsToImport = ReadFromCSV(filename);

            ToDoMatrix importedToDoMatrix = new(filename);

            foreach (ToDoItem item in itemsToImport)
            {
                importedToDoMatrix.AddItem(item);
            }

            return importedToDoMatrix;
            //
        }
    }
}